//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl {
    
    
    public partial class _Default {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// User_32_MenuDieuHanhCongTy1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_32_MenuDieuHanhCongTy User_32_MenuDieuHanhCongTy1;
        
        /// <summary>
        /// User_333_XoaXe1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_333_XoaXe User_333_XoaXe1;
        
        /// <summary>
        /// User_334_CapNhatThongTinXe1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_334_CapNhatThongTinXe User_334_CapNhatThongTinXe1;
        
        /// <summary>
        /// User_362_ThemNhanVienMoi1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_362_ThemNhanVienMoi User_362_ThemNhanVienMoi1;
        
        /// <summary>
        /// User_332_ThemXeMoi1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_332_ThemXeMoi User_332_ThemXeMoi1;
        
        /// <summary>
        /// User_411_ThongTinChuyen1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_411_ThongTinChuyen User_411_ThongTinChuyen1;
        
        /// <summary>
        /// User_342_ThemChuyenMoi1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl.User_342_ThemChuyenMoi User_342_ThemChuyenMoi1;
    }
}
