<?xml version="1.0" encoding="utf-8"?>
<Database Name="CTLH_C3" Class="TRAVEL_WEBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CTLH_C3.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CTLH_C3ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHO_NGOI" Member="CHO_NGOIs">
    <Type Name="CHO_NGOI">
      <Column Name="MaChoiNgoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHO_NGOI_DAT_CHO" Member="DAT_CHOs" ThisKey="MaChoiNgoi" OtherKey="MaChoNgoi" Type="DAT_CHO" />
    </Type>
  </Table>
  <Table Name="dbo.DAT_CHO" Member="DAT_CHOs">
    <Type Name="DAT_CHO">
      <Column Name="MaDatCho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChoNgoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuyenXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHO_NGOI_DAT_CHO" Member="CHO_NGOI" ThisKey="MaChoNgoi" OtherKey="MaChoiNgoi" Type="CHO_NGOI" IsForeignKey="true" />
      <Association Name="TINH_TRANG_DAT_CHO_DAT_CHO" Member="TINH_TRANG_DAT_CHO" ThisKey="TinhTrang" OtherKey="MaTinhTrangDatCho" Type="TINH_TRANG_DAT_CHO" IsForeignKey="true" />
      <Association Name="CHUYEN_XE_DAT_CHO" Member="CHUYEN_XE" ThisKey="MaChuyenXe" OtherKey="MaChuyenXe" Type="CHUYEN_XE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMAGE_STORE" Member="IMAGE_STOREs">
    <Type Name="IMAGE_STORE">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="IMAGE_STORE_LOAI_XE" Member="LOAI_XEs" ThisKey="Id" OtherKey="HinhAnh" Type="LOAI_XE" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY" Member="THONG_TIN_CONG_Ties" ThisKey="Id" OtherKey="Truck" Type="THONG_TIN_CONG_TY" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY1" Member="THONG_TIN_CONG_Ties1" ThisKey="Id" OtherKey="Banner" Type="THONG_TIN_CONG_TY" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY2" Member="THONG_TIN_CONG_Ties2" ThisKey="Id" OtherKey="Slogan" Type="THONG_TIN_CONG_TY" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY3" Member="THONG_TIN_CONG_Ties3" ThisKey="Id" OtherKey="Logo" Type="THONG_TIN_CONG_TY" />
      <Association Name="IMAGE_STORE_TRAM_XE" Member="TRAM_XEs" ThisKey="Id" OtherKey="HinhAnh" Type="TRAM_XE" />
      <Association Name="IMAGE_STORE_NHAN_VIEN" Member="NHAN_VIENs" ThisKey="Id" OtherKey="HinhAnh" Type="NHAN_VIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_TAI_KHOAN" Member="LOAI_TAI_KHOANs">
    <Type Name="LOAI_TAI_KHOAN">
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAI_TAI_KHOAN_TAI_KHOAN" Member="TAI_KHOANs" ThisKey="MaLoaiTaiKhoan" OtherKey="LoaiTaiKhoan" Type="TAI_KHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_XE" Member="LOAI_XEs">
    <Type Name="LOAI_XE">
      <Column Name="MaLoaiXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoCho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAI_XE_XE" Member="XEs" ThisKey="MaLoaiXe" OtherKey="MaLoaiXe" Type="XE" />
      <Association Name="IMAGE_STORE_LOAI_XE" Member="IMAGE_STORE" ThisKey="HinhAnh" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHAN_HOI" Member="PHAN_HOIs">
    <Type Name="PHAN_HOI">
      <Column Name="MaPhanHoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhanHoiKhach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHAN_HOI_KHACH_HANG_PHAN_HOI" Member="PHAN_HOI_KHACH_HANG" ThisKey="MaPhanHoiKhach" OtherKey="MaPhanHoi" Type="PHAN_HOI_KHACH_HANG" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_PHAN_HOI" Member="NHAN_VIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
      <Association Name="CHUYEN_XE_PHAN_HOI" Member="CHUYEN_XE" ThisKey="MaChuyen" OtherKey="MaChuyenXe" Type="CHUYEN_XE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHAN_HOI_KHACH_HANG" Member="PHAN_HOI_KHACH_HANGs">
    <Type Name="PHAN_HOI_KHACH_HANG">
      <Column Name="MaPhanHoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duyet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHAN_HOI_KHACH_HANG_PHAN_HOI" Member="PHAN_HOIs" ThisKey="MaPhanHoi" OtherKey="MaPhanHoiKhach" Type="PHAN_HOI" />
      <Association Name="TINH_TRANG_DUYET_PHAN_HOI_KHACH_HANG" Member="TINH_TRANG_DUYET" ThisKey="Duyet" OtherKey="MaDuyet" Type="TINH_TRANG_DUYET" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAI_KHOAN" Member="TAI_KHOANs">
    <Type Name="TAI_KHOAN">
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Salt" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayKichHoat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAI_TAI_KHOAN_TAI_KHOAN" Member="LOAI_TAI_KHOAN" ThisKey="LoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="LOAI_TAI_KHOAN" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_TAI_KHOAN" Member="NHAN_VIEN" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONG_TIN_CONG_TY" Member="THONG_TIN_CONG_Ties">
    <Type Name="THONG_TIN_CONG_TY">
      <Column Name="MaThongTinCongTy" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Banner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Truck" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Slogan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Logo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinTucGioiThieu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MaAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY" Member="IMAGE_STORE" ThisKey="Truck" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY1" Member="IMAGE_STORE1" ThisKey="Banner" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY2" Member="IMAGE_STORE2" ThisKey="Slogan" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
      <Association Name="IMAGE_STORE_THONG_TIN_CONG_TY3" Member="IMAGE_STORE3" ThisKey="Logo" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_THONG_TIN_CONG_TY" Member="NHAN_VIEN" ThisKey="MaAdmin" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINH_TRANG_CHUYEN_XE" Member="TINH_TRANG_CHUYEN_XEs">
    <Type Name="TINH_TRANG_CHUYEN_XE">
      <Column Name="MaTinhTrangChuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrangChuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TINH_TRANG_CHUYEN_XE_CHUYEN_XE" Member="CHUYEN_XEs" ThisKey="MaTinhTrangChuyen" OtherKey="TinhTrang" Type="CHUYEN_XE" />
    </Type>
  </Table>
  <Table Name="dbo.TINH_TRANG_DAT_CHO" Member="TINH_TRANG_DAT_CHOs">
    <Type Name="TINH_TRANG_DAT_CHO">
      <Column Name="MaTinhTrangDatCho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrangDatCho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TINH_TRANG_DAT_CHO_DAT_CHO" Member="DAT_CHOs" ThisKey="MaTinhTrangDatCho" OtherKey="TinhTrang" Type="DAT_CHO" />
    </Type>
  </Table>
  <Table Name="dbo.TINH_TRANG_DUYET" Member="TINH_TRANG_DUYETs">
    <Type Name="TINH_TRANG_DUYET">
      <Column Name="MaDuyet" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TINH_TRANG_DUYET_PHAN_HOI_KHACH_HANG" Member="PHAN_HOI_KHACH_HANGs" ThisKey="MaDuyet" OtherKey="Duyet" Type="PHAN_HOI_KHACH_HANG" />
    </Type>
  </Table>
  <Table Name="dbo.TINH_TRANG_XE" Member="TINH_TRANG_XEs">
    <Type Name="TINH_TRANG_XE">
      <Column Name="MaTinhTrangXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrangXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TINH_TRANG_XE_XE" Member="XEs" ThisKey="MaTinhTrangXe" OtherKey="TinhTrangXe" Type="XE" />
    </Type>
  </Table>
  <Table Name="dbo.XE" Member="XEs">
    <Type Name="XE">
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BienSoXe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTaiXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TramXeLuuTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAI_XE_XE" Member="LOAI_XE" ThisKey="MaLoaiXe" OtherKey="MaLoaiXe" Type="LOAI_XE" IsForeignKey="true" />
      <Association Name="TINH_TRANG_XE_XE" Member="TINH_TRANG_XE" ThisKey="TinhTrangXe" OtherKey="MaTinhTrangXe" Type="TINH_TRANG_XE" IsForeignKey="true" />
      <Association Name="TRAM_XE_XE" Member="TRAM_XE" ThisKey="TramXeLuuTru" OtherKey="MaTramXe" Type="TRAM_XE" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_XE" Member="NHAN_VIEN" ThisKey="MaTaiXe" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TUYEN_XE" Member="TUYEN_XEs">
    <Type Name="TUYEN_XE">
      <Column Name="MaTuyenXe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTuyenXe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTramDi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaTramDen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongChuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TanSuatChuyen" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianBatDau" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDi" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GiaVe" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LuongTaiXe" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="TUYEN_XE_CHUYEN_XE" Member="CHUYEN_XEs" ThisKey="MaTuyenXe" OtherKey="MaTuyenXe" Type="CHUYEN_XE" />
      <Association Name="TRAM_XE_TUYEN_XE" Member="TRAM_XE" ThisKey="MaTramDi" OtherKey="MaTramXe" Type="TRAM_XE" IsForeignKey="true" />
      <Association Name="TRAM_XE_TUYEN_XE1" Member="TRAM_XE1" ThisKey="MaTramDen" OtherKey="MaTramXe" Type="TRAM_XE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRAM_XE" Member="TRAM_XEs">
    <Type Name="TRAM_XE">
      <Column Name="MaTramXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTramXe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTruongTram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TRAM_XE_XE" Member="XEs" ThisKey="MaTramXe" OtherKey="TramXeLuuTru" Type="XE" />
      <Association Name="TRAM_XE_TUYEN_XE" Member="TUYEN_XEs" ThisKey="MaTramXe" OtherKey="MaTramDi" Type="TUYEN_XE" />
      <Association Name="TRAM_XE_TUYEN_XE1" Member="TUYEN_XEs1" ThisKey="MaTramXe" OtherKey="MaTramDen" Type="TUYEN_XE" />
      <Association Name="IMAGE_STORE_TRAM_XE" Member="IMAGE_STORE" ThisKey="HinhAnh" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
      <Association Name="NHAN_VIEN_TRAM_XE" Member="NHAN_VIEN" ThisKey="MaTruongTram" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAN_VIEN" Member="NHAN_VIENs">
    <Type Name="NHAN_VIEN">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuongTrongThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NHAN_VIEN_PHAN_HOI" Member="PHAN_HOIs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PHAN_HOI" />
      <Association Name="NHAN_VIEN_TAI_KHOAN" Member="TAI_KHOANs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="TAI_KHOAN" />
      <Association Name="NHAN_VIEN_THONG_TIN_CONG_TY" Member="THONG_TIN_CONG_Ties" ThisKey="MaNhanVien" OtherKey="MaAdmin" Type="THONG_TIN_CONG_TY" />
      <Association Name="NHAN_VIEN_XE" Member="XEs" ThisKey="MaNhanVien" OtherKey="MaTaiXe" Type="XE" />
      <Association Name="NHAN_VIEN_TRAM_XE" Member="TRAM_XEs" ThisKey="MaNhanVien" OtherKey="MaTruongTram" Type="TRAM_XE" />
      <Association Name="NHAN_VIEN_CHUYEN_XE" Member="CHUYEN_XEs" ThisKey="MaNhanVien" OtherKey="MaTaiXe" Type="CHUYEN_XE" />
      <Association Name="IMAGE_STORE_NHAN_VIEN" Member="IMAGE_STORE" ThisKey="HinhAnh" OtherKey="Id" Type="IMAGE_STORE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUYEN_XE" Member="CHUYEN_XEs">
    <Type Name="CHUYEN_XE">
      <Column Name="MaChuyenXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhoiHanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTuyenXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTaiXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DuKienDen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianDenTram" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LuongTaiXe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaVe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuongMuaVe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHUYEN_XE_DAT_CHO" Member="DAT_CHOs" ThisKey="MaChuyenXe" OtherKey="MaChuyenXe" Type="DAT_CHO" />
      <Association Name="CHUYEN_XE_PHAN_HOI" Member="PHAN_HOIs" ThisKey="MaChuyenXe" OtherKey="MaChuyen" Type="PHAN_HOI" />
      <Association Name="NHAN_VIEN_CHUYEN_XE" Member="NHAN_VIEN" ThisKey="MaTaiXe" OtherKey="MaNhanVien" Type="NHAN_VIEN" IsForeignKey="true" />
      <Association Name="TINH_TRANG_CHUYEN_XE_CHUYEN_XE" Member="TINH_TRANG_CHUYEN_XE" ThisKey="TinhTrang" OtherKey="MaTinhTrangChuyen" Type="TINH_TRANG_CHUYEN_XE" IsForeignKey="true" />
      <Association Name="TUYEN_XE_CHUYEN_XE" Member="TUYEN_XE" ThisKey="MaTuyenXe" OtherKey="MaTuyenXe" Type="TUYEN_XE" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.LayChuyenXe" Method="LayChuyenXe">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TaiXe" Method="TaiXe">
    <ElementType Name="TaiXeResult">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuongTrongThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Salt" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayKichHoat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhanVien1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TaiXeChuaPhanCong" Method="TaiXeChuaPhanCong">
    <ElementType Name="TaiXeChuaPhanCongResult">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuongTrongThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Salt" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayKichHoat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhanVien1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XeChuaPhanCong" Method="XeChuaPhanCong">
    <ElementType Name="XeChuaPhanCongResult">
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BienSoXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTaiXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TramXeLuuTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChuyenXeChuaPhanCong" Method="ChuyenXeChuaPhanCong">
    <ElementType Name="ChuyenXeChuaPhanCongResult">
      <Column Name="MaChuyenXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTuyenXe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KhoiHanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DuKienDen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenTramDi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTramDen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaTramXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TaiXePhanCongChuyen" Method="TaiXePhanCongChuyen">
    <Parameter Name="maChuyenXe" Type="System.Int32" DbType="Int" />
    <ElementType Name="TaiXePhanCongChuyenResult">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>